# Generated by Django 5.1.3 on 2024-11-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
