# Generated by Django 5.1.3 on 2024-11-20 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_blogs_category_blogs_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blogs_project', to='core.project'),
            preserve_default=False,
        ),
    ]
